feat: filter artworks to a sale
artsy/rosalind pull request #800
Opened 2024-08-21 18:14 UTC by joeyAghion

Like https://github.com/artsy/helix/pull/452, this adds the ability to filter to a given **sale**'s artworks for batch genoming purposes. Once again it mostly copies handling of fairs. Looks like:

<img width="381" alt="Screenshot 2024-08-21 at 2 13 27 PM" src="https://github.com/user-attachments/assets/f0c07a51-d5eb-46cd-8772-cc80ea72168b">

2024-08-22 22:26 UTC, anandaroop requested changes
I highlighted the key change below that will add the crucial UI behavior of giving you feedback about the selected sale and the ability to dismiss.

Directly analagous to how it works for fairs:

https://github.com/user-attachments/assets/34bf94e9-be46-46d2-9206-9a67a5ebc765

Also left a few suggestions for specs. Dilemma because the patterns are old, but I figure better to maintain coverage — and it should be fairly simple copypasta,

2024-08-22 22:26 UTC, anandaroop commented on app/javascript/components/batch_update/components/SearchForm.js
> +          sale={sale}
**suggestion:** This is on the right track, but we need to thread this a little further [and replicate this](https://github.com/artsy/rosalind/blob/8dac405e64f7d1164eb2b1b2211ae4decf10ebb7/app/javascript/components/batch_update/components/CurrentCriteria.js#L65) in order to have the current sale criterion (and dismiss button) actually show up in the UI.

2024-08-22 22:26 UTC, anandaroop commented on app/javascript/components/batch_update/components/SearchForm.js
> +          sale={sale}
**suggestion:** add test coverage as well, [like so](https://github.com/artsy/rosalind/blob/8dac405e64f7d1164eb2b1b2211ae4decf10ebb7/app/javascript/components/batch_update/components/CurrentCriteria.spec.js#L80-L85).

2024-08-22 22:26 UTC, anandaroop commented on app/javascript/components/batch_update/components/SearchForm.js
> +        {sale === null && <SaleAutosuggest updateState={updateState} />}
**suggestion:** Add test coverage, [like so](https://github.com/artsy/rosalind/blob/8dac405e64f7d1164eb2b1b2211ae4decf10ebb7/app/javascript/components/batch_update/components/SearchForm.spec.js#L58-L63)

2024-08-23 15:28 UTC, joeyAghion commented
Thank you 🙇 for the detailed advice. Those changes and tests were straightforward to add. (I actually sort of like the simplicity and repetition of Rosalind-era tooling.)

The new dismissable sale element looks like:
<img width="700" alt="Screenshot 2024-08-23 at 11 13 48 AM" src="https://github.com/user-attachments/assets/0243d691-f417-4416-a8f1-123b9d32e70f">

2024-08-23 15:44 UTC, anandaroop approved these changes
LGTM!

2024-08-23 15:54 UTC, merged